using System;
using System.Collections.Generic;
using System.Linq;

namespace Problem._2
{
    /*
        Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
     */

    class Program
    {
        static void Main()
        {
            var fibList = GetFibList(4000000);
            var result = fibList.Where(n => n % 2 == 0).ToList().Sum();

            Console.WriteLine("Result: " + result);
            Console.ReadKey();
        }

        static List<long> GetFibList(long limit)
        {
            var fibList = new List<long> { 1, 2 };
            long nextTerm;

            do
            {
                nextTerm = fibList.Skip(fibList.Count - 2).Sum();
                fibList.Add(nextTerm);
            }
            while (nextTerm < limit);
            
            return fibList;
        }
    }
}
